### PR TITLE
Accept default value in placeholders for unresolved property values

### PR DESCRIPTION
**Pull request by diamondT**
Hi,

Here is a patch for accepting default values when a property key is not resolved.
Default value (if present) will be returned if all other resolution attempts fail (i.e. properties -> system properties -> env variable -> default value).

A few examples:

Given these initial values

```
("host", "example.com")
("port", "9090")
("fallback", "fallback value")
```

the following replacements will happen

| raw value | replacement |
| --- | --- |
| ${unknown:} | ${unknown} |
| ${unknown:defaultValue} | defaultValue |
| http://${uhost:localhost}:${uport:8080} | http://localhost:8080 |
| http://${host:localhost}:${port:8080} | http://example.com:9090 |
| ${unknown:${fallback}} | fallback value |
| ${unknown:${double.unknown}} | ${double.unknown} |
| ${unknown:with space} | with space |
| ${unknown:with extra :} | with extra : |
| ${malformed:defVal | ${malformed:defVal |
| ${malformed:with space | ${malformed:with space |
| ${malformed:with extra : | ${malformed:with extra : |
| ${unknown::} | : |

Let me know what you think.

Thanks,

### CODE REVIEW

**Comment by khmarbaise** [comment]
If i correctly understand your code this will handle all the time the default values...I would say to add a flag which controls this behaviour and don't make it the default. Furthermore it would be nice having a documentation on the site with an example...

**Comment by diamondT** [comment]
Done.
I assume by "site" you meant the "index.apt" file. I've added a few lines there along with the examples mentioned in my previous comment.

Thanks,

**Comment by borisbrodski** [comment]
This is a really cool feature! I vote for it.

Just one note: In my opinion, `${test:}` should be considered as a property with empty default (`default=""`).
So the expansion may look like this:

raw value  | replacement
------------- | -------------
|`${unknown}`  | `${unknown}`    |
|`${unknown:}` |                          |

What do you think?

**Comment by vguna** [comment]
Sounds nice. Any news on this?

**Comment by OrangeDog** [comment]
Can this be revisited?

**Comment by oliverlockwood** [comment]
This would be incredibly useful.  Perhaps one of the project maintainers could advise what's necessary to be able to merge this in and start using it?  I'd rather not have to maintain a fork of this plugin for something which ought to be common usage!

**Comment by hinorashi** [comment]
hi guys, how about this, i'm still waiting for it :D

**Comment by eugenepaniot** [comment]
Me too, still waiting for it -(

**Comment by ProIcons** [comment]
bump

**Comment by drekbour** [comment]
2022 and still waiting...

**Review by slachiewicz — APPROVED** [review]

**Comment by drekbour** [comment]
Hmmm. I actually wanted this behaviour for vanilla `<properties>` in the `pom.xml`. Does this plugin enable that in any way?

**Comment by diamondT** [comment]
resolved some more conflicts with the base branch 🔀

**Comment by slawekjaranowski** [comment]
@diamondT thanks for PR and for patience 
This one is the oldest PR I was merged as I remember 😄

**Comment by diamondT** [comment]
better late than never :)
cheers!

**Pull request merged**
