### PR TITLE
Feature/issue 30

### LINKED ISSUE #30: write-active-profile-properties configuration param outputFile not allowed
maven throws error while processing 

```
<execution>
  <id>write-properties</id>
  <phase>generate-resources</phase>
  <goals>
    <goal>write-active-profile-properties</goal>
  </goals>
  <configuration>
    <outputFile>
     src/main/resources/maven.properties
    </outputFile>
  </configuration>
</execution>
```

With error message 
Execution write-properties of goal org.codehaus.mojo:properties-maven-plugin:1.0.0:write-active-profile-properties failed. NullPointerException

Intellij IDEA shows that Element "outputFile" is not allowed here.

write-project-properties goal works as expected

### PR DESCRIPTION
**Pull request by mykelalvis-rialtic**
Fixes #30 
Replaces #35

### CODE REVIEW

**Comment by slachiewicz** [comment]
Can you elaborate more what is scope or this pr?

**Comment by mykelalvis** [comment]
Per the top level, it fixes #30 and replaces #35.
It (and its predecessors) lay fallow for quite some time.

As for its scope, it's just meant to close #30.  As I no longer have access to `mykelalvis-rialtic`, I can't do much more that deal with what exists or create a new PR.

It might be irrelevant today, but if so then #30 should maybe be closed as "won't fix"

**Comment by mykelalvis** [comment]
If needed, I can close this PR, update my fork, and re-apply my changes.  It's (probably) not much trouble to do that.

**Comment by slawekjaranowski** [comment]
@mykelalvis as you wish I close it

**Pull request closed without merging**
